<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MaksIT.PostClient.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MaksIT.PostClient.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaksIT.Core" Version="1.6.8" />
    <PackageReference Include="MaksIT.Results" Version="2.0.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
  </ItemGroup>

</Project>
